#
#
#
---
- name: Init deploy
  hosts: localhost
  become: yes
  become_user: root
  connection: local
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "**********************************************************************************"
          - "=====================       Start Deploying mosquitto     ========================="         
          - "**********************************************************************************"
    - name:
      wait_for:
        delay: 3
        timeout: 0
    - name: Gather system time
      setup:
        filter: ansible_date_time
    - name: Set start time
      set_fact:
        time_start: "{{ ansible_date_time.epoch }}"
    - debug: var=ansible_date_time.date
    - debug: var=ansible_date_time.time

- name: Verify that the operating system version is consistent
  hosts: "{{ hosts | default('all:!keepalived-vip:!vip-port:!add-broker:!add-broker-address') }}"
  gather_facts: yes
  become: yes
  become_user: root
  any_errors_fatal: true
  tags: init
  roles:
    - { role: set-default }
    - { role: init-host }
