---
- name: Init deploy
  hosts: localhost
  become: yes
  become_user: root
  connection: local
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "**********************************************************************************"
          - "================== Start Deploying keepalived ========================="
          - "**********************************************************************************"
    - name:
      wait_for:
        delay: 3
        timeout: 0
    - name: Gather system time
      setup:
        filter: ansible_date_time
    - name: Set start time
      set_fact:
        time_start: "{{ ansible_date_time.epoch }}"
    - debug: var=ansible_date_time.date
    - debug: var=ansible_date_time.time

- name: keepalived install
  hosts: "{{ hosts | default('mosquitto-nginx-keepalived') }}"
  gather_facts: no
  become: yes
  become_user: root
  any_errors_fatal: true
  roles:
    - { role: set-default }
    - { role: keepalived }

- name: debug message
  hosts: "{{ hosts | default('mosquitto-master:mosquitto-broker') }}"
  gather_facts: no
  become: yes
  become_user: root
  any_errors_fatal: true
  tasks:
    - name: debug message
      shell: |
        echo "========================== 请在你的bridge及broker节点务必按照以下操作进行执行"
        echo "========================== cd /opt/pass/mosquitto/"
        echo "========================== bash Service_detect.sh"
      register: mosquitto_result

    - debug: msg="{{mosquitto_result.stdout_lines}}"
