---
- name: Gather system info
  setup:
    filter: ansible_*

- name: Set common vars
  set_fact:
    ipv4_address: "{% if 'address' in ansible_default_ipv4 %}{{ansible_default_ipv4.address}}{% elif 'ansible_'~default_interface in vars %}{{vars['ansible_'~default_interface].ipv4.address}}{%else%}{{ansible_all_ipv4_addresses.0}}{%endif%}"
    ipv4_interface: "{% if 'interface' in ansible_default_ipv4 %}{{ansible_default_ipv4.interface}}{% elif 'ansible_'~default_interface in vars %}{{default_interface}}{%else%}{{ansible_interfaces.0}}{%endif%}"
    ipv4_hostname: "{{hostvars[inventory_hostname]['ansible_hostname']}}" 
    centos_version: "CentOS.7.9.2009"

- name: Set flag after checked
  set_fact:
    set_default_success: yes
